<a href="https://colab.research.google.com/github/leeknnn/viktoriiashkorubska-41/blob/master/lab_work_2/lab_work_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]
avg_temp = [-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2]
precip = [38, 36, 38, 41, 53, 74, 84, 69, 47, 36, 44, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

display(df.head())
print("Форма таблиці:", df.shape)

print("Індекс за замовчуванням:", df.index)

df_by_month = df.set_index("month")
display(df_by_month.loc["Тра"])

df = df_by_month.reset_index()

df.index = range(1, 13)

print("--- Вибірка через .loc (підписи від 1 до 6) ---")
display(df.loc[1:6, "avg_temp"])

print("--- Вибірка через .iloc (позиції від 0 до 5) ---")
display(df.iloc[0:6].loc[:, "avg_temp"])

print("--- Стовпці month і precip ---")
display(df.loc[:, ["month", "precip"]])

print("Місяці, де тепліше 15°C:")
display(df[df["avg_temp"] > 15]["month"])

print("\nТеплі (>10) та вологі (>50) місяці:")
display(df[(df["avg_temp"] > 10) & (df["precip"] > 50)]["month"])

print("\nДуже холодні (<0) або дуже вологі (>80) місяці:")
display(df[(df["avg_temp"] < 0) | (df["precip"] > 80)]["month"])

df["avg_temp_f"] = df["avg_temp"] * 9/5 + 32

mean_precip = df["precip"].mean()
df["is_wet"] = df["precip"] > mean_precip

def get_season(num):
    if num in [12, 1, 2]:
        return "зима"
    elif num in [3, 4, 5]:
        return "весна"
    elif num in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

df["season"] = df.index.map(get_season)

display(df)

  month  avg_temp  precip
0   Січ        -4      38
1   Лют        -3      36
2   Бер         2      38
3   Кві         9      41
4   Тра        15      53

Форма таблиці: (12, 3)
Індекс за замовчуванням: RangeIndex(start=0, stop=12, step=1)

avg_temp    15
precip      53
Name: Тра, dtype: int64

--- Вибірка через .loc (підписи від 1 до 6) ---

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

--- Вибірка через .iloc (позиції від 0 до 5) ---

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

--- Стовпці month і precip ---

   month  precip
1    Січ      38
2    Лют      36
3    Бер      38
4    Кві      41
5    Тра      53
6    Чер      74
7    Лип      84
8    Сер      69
9    Вер      47
10   Жов      36
11   Лис      44
12   Гру      44

Місяці, де тепліше 15°C:

6    Чер
7    Лип
8    Сер
Name: month, dtype: object

Теплі (>10) та вологі (>50) місяці:

5    Тра
6    Чер
7    Лип
8    Сер
Name: month, dtype: object

Дуже холодні (<0) або дуже вологі (>80) місяці:

1     Січ
2     Лют
7     Лип
12    Гру
Name: month, dtype: object

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -4      38        24.8   False   зима
2    Лют        -3      36        26.6   False   зима
3    Бер         2      38        35.6   False  весна
4    Кві         9      41        48.2   False  весна
5    Тра        15      53        59.0    True  весна
6    Чер        19      74        66.2    True   літо
7    Лип        21      84        69.8    True   літо
8    Сер        20      69        68.0    True   літо
9    Вер        14      47        57.2   False  осінь
10   Жов         8      36        46.4   False  осінь
11   Лис         2      44        35.6   False  осінь
12   Гру        -2      44        28.4   False   зима