<a href="https://colab.research.google.com/github/leeknnn/viktoriiashkorubska-41/blob/master/lab_work_3/lab_work_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]
cloudiness = [78, 74, 68, 58, 50, 44, 40, 42, 52, 66, 76, 82]

wide = pd.DataFrame({
    "місто": ["Київ"],
    **{m: [c] for m, c in zip(months, cloudiness)}
})

display(wide)

tidy = wide.melt(id_vars="місто", var_name="місяць", value_name="хмарність")

display(tidy.head())
print("Shape:", tidy.shape)

back = tidy.pivot(index="місто", columns="місяць", values="хмарність").reset_index()
back = back[["місто"] + months]

display(back)

tidy.to_csv("variant.csv", index=False)
tidy.to_json("variant.json", orient="records", force_ascii=False)

reloaded_csv = pd.read_csv("variant.csv")
reloaded_json = pd.read_json("variant.json")

print("CSV data matches original:", tidy.equals(reloaded_csv))
print("JSON data matches original:", tidy.equals(reloaded_json))

print("\n--- CSV Content ---")
print(open("variant.csv", encoding="utf-8").read())

print("--- JSON Content ---")
print(open("variant.json", encoding="utf-8").read())

  місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Київ   78   74   68   58   50   44   40   42   52   66   76   82

  місто місяць  хмарність
0  Київ    Січ         78
1  Київ    Лют         74
2  Київ    Бер         68
3  Київ    Кві         58
4  Київ    Тра         50

Shape: (12, 3)

місяць місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0       Київ   78   74   68   58   50   44   40   42   52   66   76   82

CSV data matches original: True
JSON data matches original: True

--- CSV Content ---
місто,місяць,хмарність
Київ,Січ,78
Київ,Лют,74
Київ,Бер,68
Київ,Кві,58
Київ,Тра,50
Київ,Чер,44
Київ,Лип,40
Київ,Сер,42
Київ,Вер,52
Київ,Жов,66
Київ,Лис,76
Київ,Гру,82

--- JSON Content ---
[{"місто":"Київ","місяць":"Січ","хмарність":78},{"місто":"Київ","місяць":"Лют","хмарність":74},{"місто":"Київ","місяць":"Бер","хмарність":68},{"місто":"Київ","місяць":"Кві","хмарність":58},{"місто":"Київ","місяць":"Тра","хмарність":50},{"місто":"Київ","місяць":"Чер","хмарність":44},{"місто":"Київ","місяць":"Лип","хмарність":40},{"місто":"Київ","місяць":"Сер","хмарність":42},{"місто":"Київ","місяць":"Вер","хмарність":52},{"місто":"Київ","місяць":"Жов","хмарність":66},{"місто":"Київ","місяць":"Лис","хмарність":76},{"місто":"Київ","місяць":"Гру","хмарність":82}]